server: 
  port: 10001
  servlet:
    context-path: /ui
    

    session: 
      cookie:
       name: UISESSION
      
   
security: 
   #basic:
    # enabled: false
   oauth2:
      client:
        clientId: ClientId
        clientSecret: secret
        accessTokenUri: http://localhost:10000/auth/token
        userAuthorizationUri: http://localhost:10000/auth/oauth/authorize
        
      resource:
        userInfoUri: http://localhost:10000/auth/rest/hello
     
     
spring : 
  thymeleaf:
    cache: false      